baseURL = "http://awesome-gc.com/"
languageCode = "en-us"
title = "awesome-gc"
theme = "minimal"
#disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Will Stevens"
    description = ""
    githubUsername = "swill"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    # highlight = true
    # highlightStyle = "solarized-dark"
    # highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    # theme overrides
    css = ["css/awesome-gc.css"]
    copyright = "The contents of this website is [maintained by the community](https://github.com/swill/awesome-gc/blob/master/CONTRIBUTING.md) and is **not** an official Goverment of Canada resource."
    logo = "img/maple_leaf.png"

[[menu.main]]
    url = "/"
    name = "awesome-gc"
    weight = 1

# [[menu.main]]
#     url = "/post/"
#     name = "Posts"
#     weight = 2

# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

# [[menu.icon]]
#     url = "mailto:me@example.com"
#     name = "envelope-o"
#     weight = 1

[[menu.icon]]
    url = "https://github.com/swill/awesome-gc/"
    name = "github"
    weight = 2

# [[menu.icon]]
#     url = "https://twitter.com/opengovcan/"
#     name = "twitter"
#     weight = 3

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/username/"
#     name = "linkedin"
#     weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5
